### ISSUE TITLE
generated type doesn't escape keys

### ISSUE THREAD

**Issue by biowaffeln** [kasraghoreyshi/json-type-generator#5]
If I generate types for a JSON that looks like this:
```json
{
  "test-key": "some data"
}
```

I get the following, invalid type:
```typescript
type generatedType = {
    test-key: string
}
```

Keys should be escaped in cases where they contain characters that are invalid inside JS identifiers.

**Comment by kasraghoreyshi** [comment]
Thanks for mentioning this issue, I implemented the fix for it in the latest (v0.1.1) update.
